"""empty message

Revision ID: 148a793e0597
Revises: 57b34db5b1b2
Create Date: 2019-11-07 18:31:33.004991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '148a793e0597'
down_revision = '57b34db5b1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('commision', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('credit_card', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('ctype', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('cv', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('middle_initial', sa.String(length=2), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=25), nullable=True))
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('salary', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('stars', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'stars')
    op.drop_column('users', 'salary')
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'middle_initial')
    op.drop_column('users', 'cv')
    op.drop_column('users', 'ctype')
    op.drop_column('users', 'credit_card')
    op.drop_column('users', 'commision')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
