"""empty message

Revision ID: 57b34db5b1b2
Revises: b7f3a78c2822
Create Date: 2019-11-07 18:25:19.238564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b34db5b1b2'
down_revision = 'b7f3a78c2822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', sa.BigInteger(), nullable=True))
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_constraint('roles_user_id_fkey', 'roles', type_='foreignkey')
    op.drop_column('roles', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('roles_user_id_fkey', 'roles', 'users', ['user_id'], ['id'])
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_column('roles', 'permissions')
    # ### end Alembic commands ###
