"""empty message

Revision ID: b37fdeb79d0c
Revises: 148a793e0597
Create Date: 2019-11-08 11:50:20.899061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b37fdeb79d0c'
down_revision = '148a793e0597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
